/*----------------------------------------------------------------------------*/
/* Copyright (c) 2018 FIRST. All Rights Reserved.                             */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package org.usfirst.frc3206.FinalArtemis.commands;

import org.usfirst.frc3206.FinalArtemis.Robot;

import edu.wpi.first.wpilibj.command.ConditionalCommand;

public class HatchPosition extends ConditionalCommand {
  public HatchPosition() {
    super(new HatchDeploy(), new HatchRetract());

  // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR

  }

  @Override
  protected boolean condition(){
    if(Robot.oi.leftStick.getTriggerPressed()) {
      return true;
    } else {
      return false;
  }
}
}
