// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3206.FinalHobbes.subsystems;


import org.usfirst.frc3206.FinalHobbes.commands.*;
//import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
//import edu.wpi.first.wpilibj.PIDOutput;
//import edu.wpi.first.wpilibj.PIDSource;
import edu.wpi.first.wpilibj.Joystick;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import com.kauailabs.navx.frc.*;
import edu.wpi.first.wpilibj.I2C;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class DriveTrain extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private VictorSP LeftVictorSP;
    private VictorSP RightVictorSP;
    private DifferentialDrive HobbesDrive;
    private Encoder leftEncoder;
    private Encoder rightEncoder;
    private AHRS navxMicro = new AHRS(I2C.Port.kOnboard);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public DriveTrain() {
        //Drivetrain Motors
        LeftVictorSP = new VictorSP(0);
        RightVictorSP = new VictorSP(1);

        //Differential Drive
        HobbesDrive = new DifferentialDrive(LeftVictorSP, RightVictorSP);
        addChild("Differential Drive", HobbesDrive);
        HobbesDrive.setSafetyEnabled(true);
        HobbesDrive.setExpiration(0.1);
        HobbesDrive.setMaxOutput(1.0);
        
        //Encoders
        leftEncoder = new Encoder(0, 1, true, EncodingType.k4X);
        addChild("LeftEncoder",leftEncoder);
        leftEncoder.setDistancePerPulse(.0005);
        leftEncoder.setPIDSourceType(PIDSourceType.kRate);
        
        rightEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        addChild("RightEncoder",rightEncoder);
        rightEncoder.setDistancePerPulse(.0005);
        rightEncoder.setPIDSourceType(PIDSourceType.kRate);
        
    }

    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        setDefaultCommand(new TeleopDrive());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void takeJoystickInputs(Joystick left, Joystick right) {
    	HobbesDrive.tankDrive(left.getY() * .75, right.getY()*.75);
    }

    //Drive Functions
    public void Drive(double Speed) {
        //m_robotDrive.arcadeDrive(-Speed, 0);
        HobbesDrive.tankDrive(-Speed, -Speed * .9);
    }
    
    public void Rotate(double Speed) { 
        //m_robotDrive.arcadeDrive(Speed, 0);
        HobbesDrive.arcadeDrive(0, Speed);

    }

   public void stop() {
       HobbesDrive.tankDrive(0, 0);
   }

   //Encoders
   public double getLeftDistance() {
      return leftEncoder.getDistance();
   }

   public double getRightDistance() {
      return rightEncoder.getDistance();
   }

   public double DistanceMoved() {
    return rightEncoder.getDistance() + leftEncoder.getDistance();
}

   public void resetEncoders() {
       leftEncoder.reset();
       rightEncoder.reset();
   }

   //Navx Micro Functions
   public void resetNavX() {
       navxMicro.reset();
   }

   public double getYaw() {
    return navxMicro.getYaw();
   }

}

